# Generated by Django 3.0.8 on 2020-09-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=199, verbose_name='employee_id')),
                ('punch_in', models.TimeField(verbose_name='punch_in')),
                ('punch_out', models.TimeField(verbose_name='punch_out')),
                ('date', models.DateField(verbose_name='date')),
            ],
        ),
    ]
