# Generated by Django 3.0.8 on 2020-07-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=199, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=199, verbose_name='last_name')),
                ('email', models.CharField(max_length=199, verbose_name='email')),
                ('nic_number', models.CharField(max_length=199, verbose_name='nic_number')),
                ('phone_number', models.CharField(max_length=199, verbose_name='phone_number')),
                ('address', models.CharField(max_length=199, verbose_name='address')),
                ('designation', models.CharField(max_length=199, verbose_name='designation')),
                ('department_id', models.IntegerField(verbose_name='department_id')),
                ('image_dir', models.CharField(max_length=256, verbose_name='image_dir')),
                ('fingerprint_1', models.IntegerField(verbose_name='fingerprint_1')),
                ('fingerprint_2', models.IntegerField(verbose_name='fingerprint_2')),
                ('status', models.BooleanField(verbose_name='status')),
            ],
        ),
    ]
