# Generated by Django 3.0.8 on 2020-07-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=199, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=199, verbose_name='last_name')),
                ('email', models.CharField(max_length=199, verbose_name='email')),
                ('phone_num', models.CharField(max_length=20, verbose_name='phone_num')),
                ('user_name', models.CharField(max_length=100, verbose_name='user_name')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
                ('user_images_dir', models.CharField(max_length=200, verbose_name='user_images_dir')),
                ('finger_print_id', models.CharField(max_length=100, verbose_name='finger_print_id')),
                ('status', models.BooleanField(verbose_name='status')),
                ('forget_password_token', models.CharField(max_length=256, verbose_name='forget_password_token')),
                ('created_at', models.DateTimeField(verbose_name='create_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='update_at')),
            ],
        ),
    ]
