# Generated by Django 3.0.8 on 2020-07-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200709_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_role_id',
            field=models.IntegerField(default=0, verbose_name='user_role_id'),
            preserve_default=False,
        ),
    ]
